spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/bibliotecateste
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres